# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 20, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(30, 70, 81, 21))
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 130, 68, 17))
        self.label_2.setObjectName("label_2")
        self.ic_ele = QtWidgets.QPushButton(self.centralwidget)
        self.ic_ele.setGeometry(QtCore.QRect(90, 70, 24, 24))
        self.ic_ele.setStyleSheet("border-image:url(:/res/assets/ele.png);")
        self.ic_ele.setObjectName("ic_ele")
        self.ic_eng = QtWidgets.QPushButton(self.centralwidget)
        self.ic_eng.setGeometry(QtCore.QRect(120, 70, 24, 24))
        self.ic_eng.setStyleSheet("border-image:url(:/res/assets/eng.png);")
        self.ic_eng.setObjectName("ic_eng")
        self.ic_gua = QtWidgets.QPushButton(self.centralwidget)
        self.ic_gua.setGeometry(QtCore.QRect(150, 70, 24, 24))
        self.ic_gua.setStyleSheet("border-image:url(:/res/assets/gua.png);")
        self.ic_gua.setObjectName("ic_gua")
        self.ic_mes = QtWidgets.QPushButton(self.centralwidget)
        self.ic_mes.setGeometry(QtCore.QRect(180, 70, 24, 24))
        self.ic_mes.setStyleSheet("border-image:url(:/res/assets/mes.png);")
        self.ic_mes.setObjectName("ic_mes")
        self.ic_nec = QtWidgets.QPushButton(self.centralwidget)
        self.ic_nec.setGeometry(QtCore.QRect(210, 70, 24, 24))
        self.ic_nec.setStyleSheet("border-image:url(:/res/assets/nec.png);")
        self.ic_nec.setObjectName("ic_nec")
        self.ic_ran = QtWidgets.QPushButton(self.centralwidget)
        self.ic_ran.setGeometry(QtCore.QRect(240, 70, 24, 24))
        self.ic_ran.setStyleSheet("border-image:url(:/res/assets/ran.png);")
        self.ic_ran.setObjectName("ic_ran")
        self.ic_rev = QtWidgets.QPushButton(self.centralwidget)
        self.ic_rev.setGeometry(QtCore.QRect(270, 70, 24, 24))
        self.ic_rev.setStyleSheet("border-image:url(:/res/assets/rev.png);")
        self.ic_rev.setObjectName("ic_rev")
        self.ic_thi = QtWidgets.QPushButton(self.centralwidget)
        self.ic_thi.setGeometry(QtCore.QRect(300, 70, 24, 24))
        self.ic_thi.setStyleSheet("border-image:url(:/res/assets/thi.png);")
        self.ic_thi.setObjectName("ic_thi")
        self.ic_war = QtWidgets.QPushButton(self.centralwidget)
        self.ic_war.setGeometry(QtCore.QRect(330, 70, 24, 24))
        self.ic_war.setStyleSheet("border-image:url(:/res/assets/war.png);")
        self.ic_war.setObjectName("ic_war")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(580, 130, 99, 27))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 330, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(90, 130, 256, 181))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 335, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(90, 360, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(90, 390, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(280, 365, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(280, 395, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(280, 435, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(90, 430, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(580, 190, 99, 27))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(580, 160, 99, 27))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(580, 280, 99, 27))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(580, 250, 99, 27))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(580, 220, 99, 27))
        self.pushButton_8.setObjectName("pushButton_8")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(680, 180, 111, 81))
        self.listWidget_2.setStyleSheet("")
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(192, 192, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(98, 164, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(26, 147, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(252, 208, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 164, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(251, 62, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(76, 19, 157))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.listWidget_2.addItem(item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GW2Calculator"))
        self.label_3.setText(_translate("MainWindow", "Build Calculator"))
        self.label_1.setText(_translate("MainWindow", "Klasse"))
        self.label_2.setText(_translate("MainWindow", "Waffe"))
        self.pushButton_3.setText(_translate("MainWindow", "Head"))
        self.label.setText(_translate("MainWindow", "average Damage (light):"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Axe"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "Dagger"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "Mace"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "Pistol"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "Sword"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "Scepter"))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "Focus"))
        item = self.listWidget.item(7)
        item.setText(_translate("MainWindow", "Shield"))
        item = self.listWidget.item(8)
        item.setText(_translate("MainWindow", "Torch"))
        item = self.listWidget.item(9)
        item.setText(_translate("MainWindow", "Warhorn"))
        item = self.listWidget.item(10)
        item.setText(_translate("MainWindow", "Greatsword"))
        item = self.listWidget.item(11)
        item.setText(_translate("MainWindow", "Hammer"))
        item = self.listWidget.item(12)
        item.setText(_translate("MainWindow", "Longbow"))
        item = self.listWidget.item(13)
        item.setText(_translate("MainWindow", "Rifle"))
        item = self.listWidget.item(14)
        item.setText(_translate("MainWindow", "Short bow"))
        item = self.listWidget.item(15)
        item.setText(_translate("MainWindow", "Staff"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">0</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "average Damage (medium):"))
        self.label_6.setText(_translate("MainWindow", "average Damage (heavy):"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">0</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">0</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">0</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">hits to die</span><span style=\" font-size:10pt; vertical-align:super;\">*</span><span style=\" font-size:10pt;\">:</span></p></body></html>"))
        self.pushButton_4.setText(_translate("MainWindow", "Torso"))
        self.pushButton_5.setText(_translate("MainWindow", "shoulders"))
        self.pushButton_6.setText(_translate("MainWindow", "foot"))
        self.pushButton_7.setText(_translate("MainWindow", "leg"))
        self.pushButton_8.setText(_translate("MainWindow", "hands"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", "Basic"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("MainWindow", "Fine"))
        item = self.listWidget_2.item(2)
        item.setText(_translate("MainWindow", "Masterwork"))
        item = self.listWidget_2.item(3)
        item.setText(_translate("MainWindow", "Rare"))
        item = self.listWidget_2.item(4)
        item.setText(_translate("MainWindow", "Exotic"))
        item = self.listWidget_2.item(5)
        item.setText(_translate("MainWindow", "Ascended"))
        item = self.listWidget_2.item(6)
        item.setText(_translate("MainWindow", "Legendary"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)

import res_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

