# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tvCap = QtWidgets.QLabel(self.centralwidget)
        self.tvCap.setGeometry(QtCore.QRect(290, 20, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.tvCap.setFont(font)
        self.tvCap.setObjectName("tvCap")
        self.tvClass = QtWidgets.QLabel(self.centralwidget)
        self.tvClass.setGeometry(QtCore.QRect(30, 70, 81, 21))
        self.tvClass.setObjectName("tvClass")
        self.tvWeapon = QtWidgets.QLabel(self.centralwidget)
        self.tvWeapon.setGeometry(QtCore.QRect(30, 130, 68, 17))
        self.tvWeapon.setObjectName("tvWeapon")
        self.ic_ele = QtWidgets.QPushButton(self.centralwidget)
        self.ic_ele.setGeometry(QtCore.QRect(90, 70, 24, 24))
        self.ic_ele.setStyleSheet("border-image:url(:/res/assets/ele.png);")
        self.ic_ele.setObjectName("ic_ele")
        self.ic_eng = QtWidgets.QPushButton(self.centralwidget)
        self.ic_eng.setGeometry(QtCore.QRect(120, 70, 24, 24))
        self.ic_eng.setStyleSheet("border-image:url(:/res/assets/eng.png);")
        self.ic_eng.setObjectName("ic_eng")
        self.ic_gua = QtWidgets.QPushButton(self.centralwidget)
        self.ic_gua.setGeometry(QtCore.QRect(150, 70, 24, 24))
        self.ic_gua.setStyleSheet("border-image:url(:/res/assets/gua.png);")
        self.ic_gua.setObjectName("ic_gua")
        self.ic_mes = QtWidgets.QPushButton(self.centralwidget)
        self.ic_mes.setGeometry(QtCore.QRect(180, 70, 24, 24))
        self.ic_mes.setStyleSheet("border-image:url(:/res/assets/mes.png);")
        self.ic_mes.setObjectName("ic_mes")
        self.ic_nec = QtWidgets.QPushButton(self.centralwidget)
        self.ic_nec.setGeometry(QtCore.QRect(210, 70, 24, 24))
        self.ic_nec.setStyleSheet("border-image:url(:/res/assets/nec.png);")
        self.ic_nec.setObjectName("ic_nec")
        self.ic_ran = QtWidgets.QPushButton(self.centralwidget)
        self.ic_ran.setGeometry(QtCore.QRect(240, 70, 24, 24))
        self.ic_ran.setStyleSheet("border-image:url(:/res/assets/ran.png);")
        self.ic_ran.setObjectName("ic_ran")
        self.ic_rev = QtWidgets.QPushButton(self.centralwidget)
        self.ic_rev.setGeometry(QtCore.QRect(270, 70, 24, 24))
        self.ic_rev.setStyleSheet("border-image:url(:/res/assets/rev.png);")
        self.ic_rev.setObjectName("ic_rev")
        self.ic_thi = QtWidgets.QPushButton(self.centralwidget)
        self.ic_thi.setGeometry(QtCore.QRect(300, 70, 24, 24))
        self.ic_thi.setStyleSheet("border-image:url(:/res/assets/thi.png);")
        self.ic_thi.setObjectName("ic_thi")
        self.ic_war = QtWidgets.QPushButton(self.centralwidget)
        self.ic_war.setGeometry(QtCore.QRect(330, 70, 24, 24))
        self.ic_war.setStyleSheet("border-image:url(:/res/assets/war.png);")
        self.ic_war.setObjectName("ic_war")
        self.btnHead = QtWidgets.QPushButton(self.centralwidget)
        self.btnHead.setGeometry(QtCore.QRect(580, 130, 99, 27))
        self.btnHead.setObjectName("btnHead")
        self.tvAvgDL = QtWidgets.QLabel(self.centralwidget)
        self.tvAvgDL.setGeometry(QtCore.QRect(90, 330, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tvAvgDL.setFont(font)
        self.tvAvgDL.setObjectName("tvAvgDL")
        self.lstWeapons = QtWidgets.QListWidget(self.centralwidget)
        self.lstWeapons.setGeometry(QtCore.QRect(90, 130, 256, 181))
        self.lstWeapons.setObjectName("lstWeapons")
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.lstWeapons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstWeapons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstWeapons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstWeapons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstWeapons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstWeapons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstWeapons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstWeapons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstWeapons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstWeapons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstWeapons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstWeapons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstWeapons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstWeapons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstWeapons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstWeapons.addItem(item)
        self.tvOptDL = QtWidgets.QLabel(self.centralwidget)
        self.tvOptDL.setGeometry(QtCore.QRect(280, 335, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tvOptDL.setFont(font)
        self.tvOptDL.setObjectName("tvOptDL")
        self.tvAvgDM = QtWidgets.QLabel(self.centralwidget)
        self.tvAvgDM.setGeometry(QtCore.QRect(90, 360, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tvAvgDM.setFont(font)
        self.tvAvgDM.setObjectName("tvAvgDM")
        self.tvAvgDH = QtWidgets.QLabel(self.centralwidget)
        self.tvAvgDH.setGeometry(QtCore.QRect(90, 390, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tvAvgDH.setFont(font)
        self.tvAvgDH.setObjectName("tvAvgDH")
        self.tvOptDM = QtWidgets.QLabel(self.centralwidget)
        self.tvOptDM.setGeometry(QtCore.QRect(280, 365, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tvOptDM.setFont(font)
        self.tvOptDM.setObjectName("tvOptDM")
        self.tvOptDH = QtWidgets.QLabel(self.centralwidget)
        self.tvOptDH.setGeometry(QtCore.QRect(280, 395, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tvOptDH.setFont(font)
        self.tvOptDH.setObjectName("tvOptDH")
        self.tvOptSurvive = QtWidgets.QLabel(self.centralwidget)
        self.tvOptSurvive.setGeometry(QtCore.QRect(280, 435, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tvOptSurvive.setFont(font)
        self.tvOptSurvive.setObjectName("tvOptSurvive")
        self.tvSurvive = QtWidgets.QLabel(self.centralwidget)
        self.tvSurvive.setGeometry(QtCore.QRect(90, 430, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tvSurvive.setFont(font)
        self.tvSurvive.setObjectName("tvSurvive")
        self.btnTorso = QtWidgets.QPushButton(self.centralwidget)
        self.btnTorso.setGeometry(QtCore.QRect(580, 190, 99, 27))
        self.btnTorso.setObjectName("btnTorso")
        self.btnShoulders = QtWidgets.QPushButton(self.centralwidget)
        self.btnShoulders.setGeometry(QtCore.QRect(580, 160, 99, 27))
        self.btnShoulders.setObjectName("btnShoulders")
        self.btnFoots = QtWidgets.QPushButton(self.centralwidget)
        self.btnFoots.setGeometry(QtCore.QRect(580, 280, 99, 27))
        self.btnFoots.setObjectName("btnFoots")
        self.btnLegs = QtWidgets.QPushButton(self.centralwidget)
        self.btnLegs.setGeometry(QtCore.QRect(580, 250, 99, 27))
        self.btnLegs.setObjectName("btnLegs")
        self.btnHands = QtWidgets.QPushButton(self.centralwidget)
        self.btnHands.setGeometry(QtCore.QRect(580, 220, 99, 27))
        self.btnHands.setObjectName("btnHands")
        self.lstRare = QtWidgets.QListWidget(self.centralwidget)
        self.lstRare.setGeometry(QtCore.QRect(680, 180, 111, 81))
        self.lstRare.setStyleSheet("")
        self.lstRare.setObjectName("lstRare")
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(192, 192, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.lstRare.addItem(item)
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(98, 164, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.lstRare.addItem(item)
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(26, 147, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.lstRare.addItem(item)
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(252, 208, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.lstRare.addItem(item)
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 164, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.lstRare.addItem(item)
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(251, 62, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.lstRare.addItem(item)
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(76, 19, 157))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.lstRare.addItem(item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GW2Calculator"))
        self.tvCap.setText(_translate("MainWindow", "Build Calculator"))
        self.tvClass.setText(_translate("MainWindow", "Klasse"))
        self.tvWeapon.setText(_translate("MainWindow", "Waffe"))
        self.btnHead.setText(_translate("MainWindow", "Head"))
        self.tvAvgDL.setText(_translate("MainWindow", "average Damage (light):"))
        __sortingEnabled = self.lstWeapons.isSortingEnabled()
        self.lstWeapons.setSortingEnabled(False)
        item = self.lstWeapons.item(0)
        item.setText(_translate("MainWindow", "Axe"))
        item = self.lstWeapons.item(1)
        item.setText(_translate("MainWindow", "Dagger"))
        item = self.lstWeapons.item(2)
        item.setText(_translate("MainWindow", "Mace"))
        item = self.lstWeapons.item(3)
        item.setText(_translate("MainWindow", "Pistol"))
        item = self.lstWeapons.item(4)
        item.setText(_translate("MainWindow", "Sword"))
        item = self.lstWeapons.item(5)
        item.setText(_translate("MainWindow", "Scepter"))
        item = self.lstWeapons.item(6)
        item.setText(_translate("MainWindow", "Focus"))
        item = self.lstWeapons.item(7)
        item.setText(_translate("MainWindow", "Shield"))
        item = self.lstWeapons.item(8)
        item.setText(_translate("MainWindow", "Torch"))
        item = self.lstWeapons.item(9)
        item.setText(_translate("MainWindow", "Warhorn"))
        item = self.lstWeapons.item(10)
        item.setText(_translate("MainWindow", "Greatsword"))
        item = self.lstWeapons.item(11)
        item.setText(_translate("MainWindow", "Hammer"))
        item = self.lstWeapons.item(12)
        item.setText(_translate("MainWindow", "Longbow"))
        item = self.lstWeapons.item(13)
        item.setText(_translate("MainWindow", "Rifle"))
        item = self.lstWeapons.item(14)
        item.setText(_translate("MainWindow", "Short bow"))
        item = self.lstWeapons.item(15)
        item.setText(_translate("MainWindow", "Staff"))
        self.lstWeapons.setSortingEnabled(__sortingEnabled)
        self.tvOptDL.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">0</span></p></body></html>"))
        self.tvAvgDM.setText(_translate("MainWindow", "average Damage (medium):"))
        self.tvAvgDH.setText(_translate("MainWindow", "average Damage (heavy):"))
        self.tvOptDM.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">0</span></p></body></html>"))
        self.tvOptDH.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">0</span></p></body></html>"))
        self.tvOptSurvive.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">0</span></p></body></html>"))
        self.tvSurvive.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">hits to die</span><span style=\" font-size:10pt; vertical-align:super;\">*</span><span style=\" font-size:10pt;\">:</span></p></body></html>"))
        self.btnTorso.setText(_translate("MainWindow", "Torso"))
        self.btnShoulders.setText(_translate("MainWindow", "shoulders"))
        self.btnFoots.setText(_translate("MainWindow", "foot"))
        self.btnLegs.setText(_translate("MainWindow", "leg"))
        self.btnHands.setText(_translate("MainWindow", "hands"))
        __sortingEnabled = self.lstRare.isSortingEnabled()
        self.lstRare.setSortingEnabled(False)
        item = self.lstRare.item(0)
        item.setText(_translate("MainWindow", "Basic"))
        item = self.lstRare.item(1)
        item.setText(_translate("MainWindow", "Fine"))
        item = self.lstRare.item(2)
        item.setText(_translate("MainWindow", "Masterwork"))
        item = self.lstRare.item(3)
        item.setText(_translate("MainWindow", "Rare"))
        item = self.lstRare.item(4)
        item.setText(_translate("MainWindow", "Exotic"))
        item = self.lstRare.item(5)
        item.setText(_translate("MainWindow", "Ascended"))
        item = self.lstRare.item(6)
        item.setText(_translate("MainWindow", "Legendary"))
        self.lstRare.setSortingEnabled(__sortingEnabled)

import res_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

